name: First CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Repo
        run: |
          pwd
          ls -la

      - name: Hello
        run: echo "Hello My first CI Pipeline"
